name: longhorn-test

services:

  replica1:
    networks:
      longhorn-net:
        ipv4_address: 172.22.0.11
    volumes:
      - ./replica1:/volume
    image: longhornio/longhorn-engine:57b6abed-dirty
    command: longhorn replica --listen 0.0.0.0:9502 --size 1g /volume
    restart: unless-stopped

  replica2:
    networks:
      longhorn-net:
        ipv4_address: 172.22.0.12
    volumes:
      - ./replica2:/volume
    image: longhornio/longhorn-engine:57b6abed-dirty
    command: longhorn replica --listen 0.0.0.0:9502 --size 1g /volume
    restart: unless-stopped

  replica3:
    networks:
      longhorn-net:
        ipv4_address: 172.22.0.13
    volumes:
      - ./replica3:/volume
    image: longhornio/longhorn-engine:57b6abed-dirty
    command: longhorn replica --listen 0.0.0.0:9502 --size 1g /volume
    restart: unless-stopped

  controller1:
    networks:
      longhorn-net:
        ipv4_address: 172.22.0.21
    privileged: true
    volumes:
      - /dev:/host/dev
      - ./dev1:/dev/longhorn
      - /proc:/host/proc
      - ./workloads:/workloads
    image: longhornio/longhorn-engine:57b6abed-dirty
    command: longhorn controller --frontend tgt-blockdev --replica tcp://replica1:9502 --replica tcp://replica2:9502 --replica tcp://replica3:9502 testvol --size 1g --current-size 0 --overrideTID 1
    restart: unless-stopped
    depends_on:
      - replica1
      - replica2
      - replica3

  controller2:
    networks:
      longhorn-net:
        ipv4_address: 172.22.0.22
    privileged: true
    volumes:
      - ./dev2:/dev/longhorn
      - /dev:/host/dev
      - /proc:/host/proc
    image: longhornio/longhorn-engine:57b6abed-dirty
    command: longhorn controller --frontend tgt-blockdev --replica tcp://replica1:9502 --replica tcp://replica2:9502 --replica tcp://replica3:9502 testvol --size 1g --current-size 0 --ignoreWrites --overrideTID 2
    restart: unless-stopped
    depends_on:
      - replica1
      - replica2
      - replica3
      - controller1

  controller3:
    networks:
      longhorn-net:
        ipv4_address: 172.22.0.23
    privileged: true
    volumes:
      - ./dev3:/dev/longhorn
      - /dev:/host/dev
      - /proc:/host/proc
    image: longhornio/longhorn-engine:57b6abed-dirty
    command: longhorn controller --frontend tgt-blockdev --replica tcp://replica1:9502 --replica tcp://replica2:9502 --replica tcp://replica3:9502 testvol --size 1g --current-size 0 --ignoreWrites --overrideTID 3
    restart: unless-stopped
    depends_on:
      - replica1
      - replica2
      - replica3
      - controller1

networks:
  longhorn-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
